# Project: YulsBalls
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = YulsBalls.o
LINKOBJ  = YulsBalls.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2-devel-2.0.12-mingw/SDL2-2.0.12/x86_64-w64-mingw32/lib" -L"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2_mixer-devel-2.0.4-mingw/SDL2_mixer-2.0.4/x86_64-w64-mingw32/lib" -L"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/x86_64-w64-mingw32/lib" -lopengl32 -lfreeglut -lglu32 -lmingw32 -lSDL2main -lSDL2 -lSDL2_mixer -lwinmm
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2-devel-2.0.12-mingw/SDL2-2.0.12/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2_mixer-devel-2.0.4-mingw/SDL2_mixer-2.0.4/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2-devel-2.0.12-mingw/SDL2-2.0.12/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/SDL2_mixer-devel-2.0.4-mingw/SDL2_mixer-2.0.4/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/yulen/OneDrive/Documentos/COMPUTACION GRAFICA/Yuls Balls/x86_64-w64-mingw32/include"
BIN      = YulsBalls.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

YulsBalls.o: YulsBalls.cpp
	$(CPP) -c YulsBalls.cpp -o YulsBalls.o $(CXXFLAGS)
